services:
  # api:
  #   build:
  #     context: ./diamond-backend/diamond
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "./diamond-backend:/api"
  #   env_file:
  #     - ./diamond-backend/diamond/.env
  #   depends_on:
  #     - postgres

  # frontend:
  #   build:
  #     context: ./frontend/diamond-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - "./frontend/diamond-ui:/frontend/diamond-ui"
  #   env_file:
  #     - "./frontend/diamond-ui/.env"
  #   depends_on:
  #     - api

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=diamond_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5430:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  # redis:
  #   image: 'redis:latest'
  #   ports:
  #     - '6379:6379'

volumes:
  postgres_data:
