services:
  postgres:
      image: 'postgres:latest'
      env_file:
        - .env
      ports:
        - '5432:5432'
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
  redis:
      image: 'redis:latest'
      ports:
        - '6379:6379'
  rabbitmq:
    # image: rabbitmq:3-management
    image: rabbitmq:latest
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - 5672:5672
      #- 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build:
      context: ./diamond-backend/diamond
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - "./diamond-backend:/api"
    # env_file:
    #   - ./diamond-backend/diamond/.env
    depends_on:
      postgres:
        condition: service_healthy

  # py-service:
  #   build:
  #     context: ./diamond_py
  #     dockerfile: Dockerfile
  #   ports:
  #     - "50051:50051"
  #   volumes:
  #     - "./diamond_py:/py-service"
  #   env_file:
  #     - ./diamond_py/.env
  #   depends_on:
  #     - postgres
  
  # frontend:
  #   build:
  #     context: ./frontend/diamond-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - "./frontend/diamond-ui:/frontend/diamond-ui"
  #   env_file:
  #     - "./frontend/diamond-ui/.env"
  #   depends_on:
  #     - api

volumes:
  postgres_data:
  #rabbitmq_data:
