# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: my_grpc/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'my_grpc/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15my_grpc/service.proto\x12\x1f\x63om.diamond.diamond.grpc_client\"@\n\x16\x43reateWalletSetRequest\x12\x17\n\nwalletName\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_walletName\"%\n\x17\x43reateWalletSetResponse\x12\n\n\x02id\x18\x01 \x01(\t\"V\n\x13\x43reateWalletRequest\x12\x12\n\nblockchain\x18\x01 \x01(\t\x12\x13\n\x0bwalletSetId\x18\x02 \x01(\t\x12\x16\n\x0eidempotencyKey\x18\x03 \x01(\t\"g\n\x14\x43reateWalletsRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x13\n\x0b\x62lockchains\x18\x02 \x03(\t\x12\x13\n\x0bwalletSetId\x18\x03 \x01(\t\x12\x16\n\x0eidempotencyKey\x18\x04 \x01(\t\"\xc0\x01\n\x14\x43reateWalletResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nblockchain\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x12\n\ncreateDate\x18\x04 \x01(\t\x12\x13\n\x0b\x63ustodyType\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x13\n\x0bwalletSetId\x18\x07 \x01(\t\x12\x11\n\taccountId\x18\x08 \x01(\t\x12\x18\n\x10initialPublicKey\x18\t \x01(\t\"_\n\x15\x43reateWalletsResponse\x12\x46\n\x07wallets\x18\x01 \x03(\x0b\x32\x35.com.diamond.diamond.grpc_client.CreateWalletResponse2\x93\x03\n\x06\x43ircle\x12\x86\x01\n\x0f\x43reateWalletSet\x12\x37.com.diamond.diamond.grpc_client.CreateWalletSetRequest\x1a\x38.com.diamond.diamond.grpc_client.CreateWalletSetResponse\"\x00\x12\x80\x01\n\rCreateWallets\x12\x35.com.diamond.diamond.grpc_client.CreateWalletsRequest\x1a\x36.com.diamond.diamond.grpc_client.CreateWalletsResponse\"\x00\x12}\n\x0c\x43reateWallet\x12\x34.com.diamond.diamond.grpc_client.CreateWalletRequest\x1a\x35.com.diamond.diamond.grpc_client.CreateWalletResponse\"\x00\x42#\n\x1f\x63om.diamond.diamond.grpc_clientP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_grpc.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.diamond.diamond.grpc_clientP\001'
  _globals['_CREATEWALLETSETREQUEST']._serialized_start=58
  _globals['_CREATEWALLETSETREQUEST']._serialized_end=122
  _globals['_CREATEWALLETSETRESPONSE']._serialized_start=124
  _globals['_CREATEWALLETSETRESPONSE']._serialized_end=161
  _globals['_CREATEWALLETREQUEST']._serialized_start=163
  _globals['_CREATEWALLETREQUEST']._serialized_end=249
  _globals['_CREATEWALLETSREQUEST']._serialized_start=251
  _globals['_CREATEWALLETSREQUEST']._serialized_end=354
  _globals['_CREATEWALLETRESPONSE']._serialized_start=357
  _globals['_CREATEWALLETRESPONSE']._serialized_end=549
  _globals['_CREATEWALLETSRESPONSE']._serialized_start=551
  _globals['_CREATEWALLETSRESPONSE']._serialized_end=646
  _globals['_CIRCLE']._serialized_start=649
  _globals['_CIRCLE']._serialized_end=1052
# @@protoc_insertion_point(module_scope)
